steps:
    - command: "docker-compose -f docker-compose.yml -f docker-compose.phpunit.yml up -d && docker-compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit /app/bin/install-wp-tests.sh wordpress_test root '' mysql_phpunit latest true && docker-compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit phpunit"
    label: "WP Version: 5.0.11 PHP Version: 5.6"
    soft_fail:
        - exit_status: 255
    env:
        WP_VERSION: "5.0.11"
        PHP_VERSION: "5.6"

    - command: "docker-compose -f docker-compose.yml -f docker-compose.phpunit.yml up -d && docker-compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit /app/bin/install-wp-tests.sh wordpress_test root '' mysql_phpunit latest true && docker-compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit phpunit"
      label: "WP Version: 5.5.3 PHP Version: 7.3"
      soft_fail:
          - exit_status: 255
      env:
        WP_VERSION: "5.5.3"
        PHP_VERSION: "7.3"
