steps:

  - label: "Pull PHP 5.6"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:5.6"
    retry:
      automatic: true

  - wait

  - label: "Pull PHP 7.0"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.0"
    retry:
      automatic: true

  - label: "Pull PHP 7.1"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.1"
    retry:
      automatic: true

  - wait

  - label: "Pull PHP 7.2"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.2"
    retry:
      automatic: true

  - label: "Pull PHP 7.3"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.3"
    retry:
      automatic: true

  - wait

  - label: "Pull PHP 7.4"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.4"
    retry:
      automatic: true

  - label: "Pull MariaDB"
    command: "docker pull mariadb:10.2"
    retry:
      automatic: true

  - wait

  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: 4.9.15
      WP_MULTISITE: "0"
    label: 'PHP: 5.6 | WP: 4.9.15 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: 5.0.10
      WP_MULTISITE: "0"
    label: 'PHP: 5.6 | WP: 5.0.10 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: 5.1.6
      WP_MULTISITE: "0"
    label: 'PHP: 5.6 | WP: 5.1.6 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: 5.2.7
      WP_MULTISITE: "0"
    label: 'PHP: 5.6 | WP: 5.2.7 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: 5.3.4
      WP_MULTISITE: "0"
    label: 'PHP: 5.6 | WP: 5.3.4 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: 5.4.2
      WP_MULTISITE: "0"
    label: 'PHP: 5.6 | WP: 5.4.2 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: 5.5.3
      WP_MULTISITE: "0"
    label: 'PHP: 5.6 | WP: 5.5.3 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: latest
      WP_MULTISITE: "0"
    label: 'PHP: 5.6 | WP: latest | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "5.6"
      TEST_WP_VERSION: latest
      WP_MULTISITE: "1"
    label: 'PHP: 5.6 | WP: latest | Multisite: Yes'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.0"
      TEST_WP_VERSION: 4.9.15
      WP_MULTISITE: "0"
    label: 'PHP: 7.0 | WP: 4.9.15 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.0"
      TEST_WP_VERSION: 5.0.10
      WP_MULTISITE: "0"
    label: 'PHP: 7.0 | WP: 5.0.10 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.0"
      TEST_WP_VERSION: 5.1.6
      WP_MULTISITE: "0"
    label: 'PHP: 7.0 | WP: 5.1.6 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.0"
      TEST_WP_VERSION: 5.2.7
      WP_MULTISITE: "0"
    label: 'PHP: 7.0 | WP: 5.2.7 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.0"
      TEST_WP_VERSION: 5.3.4
      WP_MULTISITE: "0"
    label: 'PHP: 7.0 | WP: 5.3.4 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.0"
      TEST_WP_VERSION: 5.4.2
      WP_MULTISITE: "0"
    label: 'PHP: 7.0 | WP: 5.4.2 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.0"
      TEST_WP_VERSION: 5.5.3
      WP_MULTISITE: "0"
    label: 'PHP: 7.0 | WP: 5.5.3 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.0"
      TEST_WP_VERSION: latest
      WP_MULTISITE: "0"
    label: 'PHP: 7.0 | WP: latest | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.1"
      TEST_WP_VERSION: 4.9.15
      WP_MULTISITE: "0"
    label: 'PHP: 7.1 | WP: 4.9.15 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.1"
      TEST_WP_VERSION: 5.0.10
      WP_MULTISITE: "0"
    label: 'PHP: 7.1 | WP: 5.0.10 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.1"
      TEST_WP_VERSION: 5.1.6
      WP_MULTISITE: "0"
    label: 'PHP: 7.1 | WP: 5.1.6 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.1"
      TEST_WP_VERSION: 5.2.7
      WP_MULTISITE: "0"
    label: 'PHP: 7.1 | WP: 5.2.7 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.1"
      TEST_WP_VERSION: 5.3.4
      WP_MULTISITE: "0"
    label: 'PHP: 7.1 | WP: 5.3.4 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.1"
      TEST_WP_VERSION: 5.4.2
      WP_MULTISITE: "0"
    label: 'PHP: 7.1 | WP: 5.4.2 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.1"
      TEST_WP_VERSION: 5.5.3
      WP_MULTISITE: "0"
    label: 'PHP: 7.1 | WP: 5.5.3 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.1"
      TEST_WP_VERSION: latest
      WP_MULTISITE: "0"
    label: 'PHP: 7.1 | WP: latest | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.2"
      TEST_WP_VERSION: 4.9.15
      WP_MULTISITE: "0"
    label: 'PHP: 7.2 | WP: 4.9.15 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.2"
      TEST_WP_VERSION: 5.0.10
      WP_MULTISITE: "0"
    label: 'PHP: 7.2 | WP: 5.0.10 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.2"
      TEST_WP_VERSION: 5.1.6
      WP_MULTISITE: "0"
    label: 'PHP: 7.2 | WP: 5.1.6 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.2"
      TEST_WP_VERSION: 5.2.7
      WP_MULTISITE: "0"
    label: 'PHP: 7.2 | WP: 5.2.7 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.2"
      TEST_WP_VERSION: 5.3.4
      WP_MULTISITE: "0"
    label: 'PHP: 7.2 | WP: 5.3.4 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.2"
      TEST_WP_VERSION: 5.4.2
      WP_MULTISITE: "0"
    label: 'PHP: 7.2 | WP: 5.4.2 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.2"
      TEST_WP_VERSION: 5.5.3
      WP_MULTISITE: "0"
    label: 'PHP: 7.2 | WP: 5.5.3 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.2"
      TEST_WP_VERSION: latest
      WP_MULTISITE: "0"
    label: 'PHP: 7.2 | WP: latest | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.3"
      TEST_WP_VERSION: 5.0.10
      WP_MULTISITE: "0"
    label: 'PHP: 7.3 | WP: 5.0.10 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.3"
      TEST_WP_VERSION: 5.1.6
      WP_MULTISITE: "0"
    label: 'PHP: 7.3 | WP: 5.1.6 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.3"
      TEST_WP_VERSION: 5.2.7
      WP_MULTISITE: "0"
    label: 'PHP: 7.3 | WP: 5.2.7 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.3"
      TEST_WP_VERSION: 5.3.4
      WP_MULTISITE: "0"
    label: 'PHP: 7.3 | WP: 5.3.4 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.3"
      TEST_WP_VERSION: 5.4.2
      WP_MULTISITE: "0"
    label: 'PHP: 7.3 | WP: 5.4.2 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.3"
      TEST_WP_VERSION: 5.5.3
      WP_MULTISITE: "0"
    label: 'PHP: 7.3 | WP: 5.5.3 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.3"
      TEST_WP_VERSION: latest
      WP_MULTISITE: "0"
    label: 'PHP: 7.3 | WP: latest | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.4"
      TEST_WP_VERSION: 5.3.4
      WP_MULTISITE: "0"
    label: 'PHP: 7.4 | WP: 5.3.4 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.4"
      TEST_WP_VERSION: 5.4.2
      WP_MULTISITE: "0"
    label: 'PHP: 7.4 | WP: 5.4.2 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.4"
      TEST_WP_VERSION: 5.5.3
      WP_MULTISITE: "0"
    label: 'PHP: 7.4 | WP: 5.5.3 | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
  - env:
      TEST_INPLACE: "0"
      TEST_PHP_VERSION: "7.4"
      TEST_WP_VERSION: latest
      WP_MULTISITE: "0"
    label: 'PHP: 7.4 | WP: latest | Multisite: No'
    plugins:
      - docker-compose#v3.7.0:
          config: docker-compose-phpunit.yml
          env:
            - WP_MULTISITE
            - TEST_INPLACE
          propagate-uid-gid: true
          pull-retries: 3
          run: wordpress
