steps:
    - label: 'PHP: 5.3 | WP: 4.4.23 | Multisite: No'
      env:
          TEST_WP_VERSION: 4.4.23
          TEST_PHP_VERSION: "5.3"
          WP_MULTISITE: 0
          TEST_INPLACE: 0
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              propagate-uid-gid: true
              run: wordpress
              env:
                  - WP_MULTISITE
                  - TEST_INPLACE
