steps:

  - label: "Pull PHP 5.6"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:5.6"
    retry:
      automatic: true

  - wait

  - label: "Pull PHP 7.0"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.0"
    retry:
      automatic: true

  - label: "Pull PHP 7.1"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.1"
    retry:
      automatic: true

  - wait

  - label: "Pull PHP 7.2"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.2"
    retry:
      automatic: true

  - label: "Pull PHP 7.3"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.3"
    retry:
      automatic: true

  - wait

  - label: "Pull PHP 7.4"
    command: "docker pull public.ecr.aws/q7y6e9n2/unit-test-images/php:7.4"
    retry:
      automatic: true

  - label: "Pull MariaDB"
    command: "docker pull mariadb:10.2"
    retry:
      automatic: true

  - wait

  - command: .buildkite/pipeline.sh | buildkite-agent pipeline upload
    label: ":pipeline: Upload"
