steps:
    - label: 'PHP: 5.3 | WP: 4.4.23 | Multisite: No'
      env:
          TEST_WP_VERSION: 4.4.23
          TEST_PHP_VERSION: "5.3"
          WP_MULTISITE: 0
          TEST_INPLACE: 0
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              propagate-uid-gid: true
              run: wordpress
              env:
                  - WP_MULTISITE
                  - TEST_INPLACE
    - label: 'PHP: 5.4 | WP: 4.5.22 | Multisite: No'
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              env:
                  - TEST_WP_VERSION=4.5.22
                  - TEST_PHP_VERSION=5.4
                  - WP_MULTISITE=0
                  - TEST_INPLACE=1
              propagate-uid-gid: true
              run: wordpress
    - label: 'PHP: 5.5 | WP: 4.7.18 | Multisite: No'
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              env:
                  - TEST_WP_VERSION=4.7.18
                  - TEST_PHP_VERSION=5.5
                  - WP_MULTISITE=0
                  - TEST_INPLACE=1
              propagate-uid-gid: true
              run: wordpress
    - label: 'PHP: 5.6 | WP: 5.0.10 | Multisite: No'
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              env:
                  - TEST_WP_VERSION=5.0.10
                  - TEST_PHP_VERSION=5.6
                  - WP_MULTISITE=0
                  - TEST_INPLACE=1
              propagate-uid-gid: true
              run: wordpress
    - label: 'PHP: 7.0 | WP: latest | Multisite: No'
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              env:
                  - TEST_WP_VERSION=latest
                  - TEST_PHP_VERSION=7.0
                  - WP_MULTISITE=0
                  - TEST_INPLACE=1
              propagate-uid-gid: true
              run: wordpress
    - label: 'PHP: 7.1 | WP: latest | Multisite: No'
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              env:
                  - TEST_WP_VERSION=latest
                  - TEST_PHP_VERSION=7.1
                  - WP_MULTISITE=0
                  - TEST_INPLACE=1
              propagate-uid-gid: true
              run: wordpress
    - label: 'PHP: 7.2 | WP: latest | Multisite: No'
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              env:
                  - TEST_WP_VERSION=latest
                  - TEST_PHP_VERSION=7.2
                  - WP_MULTISITE=0
                  - TEST_INPLACE=1
              propagate-uid-gid: true
              run: wordpress
    - label: 'PHP: 7.3 | WP: latest | Multisite: No'
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              env:
                  - TEST_WP_VERSION=latest
                  - TEST_PHP_VERSION=7.3
                  - WP_MULTISITE=0
                  - TEST_INPLACE=1
              propagate-uid-gid: true
              run: wordpress
    - label: 'PHP: 7.4 | WP: latest | Multisite: No'
      plugins:
          docker-compose#v3.7.0:
              config: docker-compose-phpunit.yml
              env:
                  - TEST_WP_VERSION=latest
                  - TEST_PHP_VERSION=7.4
                  - WP_MULTISITE=0
                  - TEST_INPLACE=1
              propagate-uid-gid: true
              run: wordpress
