<?php
/**
 * Import Functions
 *
 * These are functions are used for import data into Easy Digital Downloads.
 *
 * @package     EDD
 * @subpackage  Admin/Import
 * @copyright   Copyright (c) 2015, Pippin Williamson
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit;

function edd_do_ajax_import_file_upload() {

	if ( ! function_exists( 'wp_handle_upload' ) ) {
		require_once( ABSPATH . 'wp-admin/includes/file.php' );
	}

	require_once EDD_PLUGIN_DIR . 'includes/admin/import/class-batch-import.php';

	if( ! wp_verify_nonce( $_REQUEST['edd_ajax_import'], 'edd_ajax_import' ) ) {
		wp_send_json_error( array( 'error' => __( 'Nonce verification failed', 'edd' ) ) );
	}

	if( ! current_user_can( 'manage_shop_settings' ) ) {
		wp_send_json_error( array( 'error' => __( 'You do not have permission to import data', 'edd' ) ) );
	}

	// Let WordPress import the file. We will remove it after import is complete
	$import_file = wp_handle_upload( $_FILES['edd-import-file'], array( 'test_form' => false ) );

	if ( $import_file && empty( $import_file['error'] ) ) {

		do_action( 'edd_batch_import_class_include', $_POST['edd-import-class'] );

		$import = new $_POST['edd-import-class']( $import_file['file'] );

		wp_send_json_success( array(
			'form'    => $_POST,
			'class'   => $_POST['edd-import-class'],
			'upload'  => $import_file,
			'columns' => $import->get_columns(),
			'nonce'   => wp_create_nonce( 'edd_ajax_import', 'edd_ajax_import' )
		) );

	} else {

		/**
		 * Error generated by _wp_handle_upload()
		 * @see _wp_handle_upload() in wp-admin/includes/file.php
		 */
		
		wp_send_json_error( array( 'error' => $import_file['error'] ) );
	}

	exit;

}
add_action( 'edd_upload_import_file', 'edd_do_ajax_import_file_upload' );

/**
 * Process batch imports via ajax
 *
 * @since 2.6
 * @return void
 */
function edd_do_ajax_import() {

	require_once EDD_PLUGIN_DIR . 'includes/admin/import/class-batch-import.php';

	if( ! wp_verify_nonce( $_REQUEST['nonce'], 'edd_ajax_import' ) ) {
		wp_send_json_error( array( 'error' => __( 'Nonce verification failed', 'edd' ), 'request' => $_REQUEST ) );
	}

	if( empty( $_REQUEST['class'] ) ) {
		wp_send_json_error( array( 'error' => __( 'Missing import parameters. Import class must be specified.', 'edd' ), 'request' => $_REQUEST ) );
	}

	if( empty( $_REQUEST['upload'] ) ) {
		wp_send_json_error( array( 'error' => __( 'Missing import file. Please provide an import file.', 'edd' ), 'request' => $_REQUEST ) );
	}

	if( empty( $_REQUEST['upload']['type'] ) || 'text/csv' !== $_REQUEST['upload']['type'] ) {
		wp_send_json_error( array( 'error' => __( 'The file you uploaded does not appear to be a CSV file.', 'edd' ), 'request' => $_REQUEST ) );
	}

	if( ! file_exists( $_REQUEST['upload']['file'] ) ) {
		wp_send_json_error( array( 'error' => __( 'Something went wrong during the upload process, please try again.', 'edd' ), 'request' => $_REQUEST ) );
	}

	do_action( 'edd_batch_import_class_include', $_REQUEST['class'] );

	$step     = absint( $_REQUEST['step'] );
	$class    = $_REQUEST['class'];
	$import   = new $class( $_REQUEST['upload']['file'], $step );

	if( ! $import->can_import() ) {

		wp_send_json_error( array( 'error' => __( 'You do not have permission to import data', 'edd' ) ) );		

	}

	$field_mapping = array(
		'post_title'   => '',
		'post_name'    => '',
		'post_status'  => 'draft',
		'post_author'  => '',
		'post_date'    => '',
		'post_content' => '',
		'post_excerpt' => '',
		'price'        => '',
		'files'        => '',
		'categories'   => '',
		'tags'         => '',
		'notes'        => ''
	);

	parse_str( $_REQUEST['mapping'], $map );

	foreach( $map['edd-import-csv-column'] as $key => $column ) {

		$field_mapping[ $map['edd-import-download-field'][ $key ] ] = $column;

	}

	$import->field_mapping = $field_mapping;

	$ret = $import->process_step( $step );

	$percentage = $import->get_percentage_complete();

	if( $ret ) {

		$step += 1;
		wp_send_json_success( array(
			'step'       => $step,
			'percentage' => $percentage,
			'columns'    => $import->get_columns(),
			'mapping'    => $field_mapping
		) );

	} elseif ( true === $import->is_empty ) {

		wp_send_json_error( array(
			'error' => __( 'No data found for import parameters', 'edd' )
		) );		

	} else {

		wp_send_json_success( array(
			'step'    => 'done',
			'message' => __( 'Import complete!', 'edd' )
		) );

	}
}
add_action( 'wp_ajax_edd_do_ajax_import', 'edd_do_ajax_import' );