<?php
/**
 * Exports Functions
 *
 * These are functions are used for exporting data from Easy Digital Downloads.
 *
 * @package     EDD
 * @subpackage  Admin/Export
 * @copyright   Copyright (c) 2015, Pippin Williamson
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit;

require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/class-export.php';

/**
 * Process batch exports via ajax
 *
 * @since 2.4
 * @return void
 */
function edd_do_ajax_export() {

	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export.php';
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-payments.php';
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-customers.php';
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-file-downloads.php';

	parse_str( $_POST['form'], $form );

	$_REQUEST = $form = (array) $form;

	if( ! wp_verify_nonce( $_REQUEST['edd_ajax_export'], 'edd_ajax_export' ) ) {
		die( '-2' );
	}
	
	$step     = absint( $_POST['step'] );
	$class    = $form['edd-export-class'];
	$export   = new $class( $step );

	if( ! $export->can_export() ) {
		die( '-1' );
	}

	$export->start    = isset( $_REQUEST['start'] )             ?  sanitize_text_field( $_REQUEST['start'] )  : '';
	$export->end      = isset( $_REQUEST['end']  )              ?  sanitize_text_field( $_REQUEST['end']  )   : '';
	$export->status   = isset( $_REQUEST['status']  )           ? sanitize_text_field( $_REQUEST['status']  ) : 'complete';
	$export->download = isset( $_REQUEST['download']  )         ? absint( $_REQUEST['download']  )            : null;
	$export->price_id = isset( $_REQUEST['edd_price_option']  ) ? absint( $_REQUEST['edd_price_option']  )    : null;

	$ret = $export->process_step( $step );

	$percentage = $export->get_percentage_complete();

	if( $ret ) {

		$step += 1;
		echo json_encode( array( 'step' => $step, 'percentage' => $percentage ) ); exit;

	} else {

		$args = array_merge( $_REQUEST, array(
			'step'       => $step,
			'class'      => $class,
			'nonce'      => wp_create_nonce( 'edd-batch-export' ),
			'edd_action' => 'download_batch_export',
		) );

		$download_url = add_query_arg( $args, admin_url() );

		echo json_encode( array( 'step' => 'done', 'url' => $download_url ) ); exit;

	}
}
add_action( 'wp_ajax_edd_do_ajax_export', 'edd_do_ajax_export' );

/**
 * Process the download file generated by a batch export
 *
 * @since 2.4
 * @return void
 */
function edd_process_batch_export_download() {

	if( ! wp_verify_nonce( $_REQUEST['nonce'], 'edd-batch-export' ) ) {
		wp_die( __( 'Nonce verification failed', 'edd' ), __( 'Error', 'edd' ), array( 'response' => 403 ) );
	}

	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export.php';
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-payments.php';
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-customers.php';
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/export/class-batch-export-file-downloads.php';

	$export = new $_REQUEST['class'];
	$export->export();

}
add_action( 'edd_download_batch_export', 'edd_process_batch_export_download' );

/**
 * Exports earnings for a specified time period
 * EDD_Earnings_Export class.
 *
 * @since 2.0
 * @return void
 */
function edd_export_earnings() {
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/class-export-earnings.php';

	$earnings_export = new EDD_Earnings_Export();

	$earnings_export->export();
}
add_action( 'edd_earnings_export', 'edd_export_earnings' );


/**
 * Export all the customers to a CSV file.
 *
 * Note: The WordPress Database API is being used directly for performance
 * reasons (workaround of calling all posts and fetch data respectively)
 *
 * @since 1.4.4
 * @return void
 */
function edd_export_all_customers() {
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/class-export-customers.php';

	$customer_export = new EDD_Customers_Export();

	$customer_export->export();
}
add_action( 'edd_email_export', 'edd_export_all_customers' );

/**
 * Exports all the downloads to a CSV file using the EDD_Export class.
 *
 * @since 1.4.4
 * @return void
 */
function edd_export_all_downloads_history() {
	require_once EDD_PLUGIN_DIR . 'includes/admin/reporting/class-export-download-history.php';

	$file_download_export = new EDD_Download_History_Export();

	$file_download_export->export();
}
add_action( 'edd_downloads_history_export', 'edd_export_all_downloads_history' );