<?php

// File generated from our OpenAPI spec

namespace EDD\Vendor\Stripe\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \EDD\Vendor\Stripe\Account::OBJECT_NAME => \EDD\Vendor\Stripe\Account::class,
        \EDD\Vendor\Stripe\AccountLink::OBJECT_NAME => \EDD\Vendor\Stripe\AccountLink::class,
        \EDD\Vendor\Stripe\AlipayAccount::OBJECT_NAME => \EDD\Vendor\Stripe\AlipayAccount::class,
        \EDD\Vendor\Stripe\ApplePayDomain::OBJECT_NAME => \EDD\Vendor\Stripe\ApplePayDomain::class,
        \EDD\Vendor\Stripe\ApplicationFee::OBJECT_NAME => \EDD\Vendor\Stripe\ApplicationFee::class,
        \EDD\Vendor\Stripe\ApplicationFeeRefund::OBJECT_NAME => \EDD\Vendor\Stripe\ApplicationFeeRefund::class,
        \EDD\Vendor\Stripe\Balance::OBJECT_NAME => \EDD\Vendor\Stripe\Balance::class,
        \EDD\Vendor\Stripe\BalanceTransaction::OBJECT_NAME => \EDD\Vendor\Stripe\BalanceTransaction::class,
        \EDD\Vendor\Stripe\BankAccount::OBJECT_NAME => \EDD\Vendor\Stripe\BankAccount::class,
        \EDD\Vendor\Stripe\BillingPortal\Configuration::OBJECT_NAME => \EDD\Vendor\Stripe\BillingPortal\Configuration::class,
        \EDD\Vendor\Stripe\BillingPortal\Session::OBJECT_NAME => \EDD\Vendor\Stripe\BillingPortal\Session::class,
        \EDD\Vendor\Stripe\BitcoinReceiver::OBJECT_NAME => \EDD\Vendor\Stripe\BitcoinReceiver::class,
        \EDD\Vendor\Stripe\BitcoinTransaction::OBJECT_NAME => \EDD\Vendor\Stripe\BitcoinTransaction::class,
        \EDD\Vendor\Stripe\Capability::OBJECT_NAME => \EDD\Vendor\Stripe\Capability::class,
        \EDD\Vendor\Stripe\Card::OBJECT_NAME => \EDD\Vendor\Stripe\Card::class,
        \EDD\Vendor\Stripe\CashBalance::OBJECT_NAME => \EDD\Vendor\Stripe\CashBalance::class,
        \EDD\Vendor\Stripe\Charge::OBJECT_NAME => \EDD\Vendor\Stripe\Charge::class,
        \EDD\Vendor\Stripe\Checkout\Session::OBJECT_NAME => \EDD\Vendor\Stripe\Checkout\Session::class,
        \EDD\Vendor\Stripe\Collection::OBJECT_NAME => \EDD\Vendor\Stripe\Collection::class,
        \EDD\Vendor\Stripe\CountrySpec::OBJECT_NAME => \EDD\Vendor\Stripe\CountrySpec::class,
        \EDD\Vendor\Stripe\Coupon::OBJECT_NAME => \EDD\Vendor\Stripe\Coupon::class,
        \EDD\Vendor\Stripe\CreditNote::OBJECT_NAME => \EDD\Vendor\Stripe\CreditNote::class,
        \EDD\Vendor\Stripe\CreditNoteLineItem::OBJECT_NAME => \EDD\Vendor\Stripe\CreditNoteLineItem::class,
        \EDD\Vendor\Stripe\Customer::OBJECT_NAME => \EDD\Vendor\Stripe\Customer::class,
        \EDD\Vendor\Stripe\CustomerBalanceTransaction::OBJECT_NAME => \EDD\Vendor\Stripe\CustomerBalanceTransaction::class,
        \EDD\Vendor\Stripe\Discount::OBJECT_NAME => \EDD\Vendor\Stripe\Discount::class,
        \EDD\Vendor\Stripe\Dispute::OBJECT_NAME => \EDD\Vendor\Stripe\Dispute::class,
        \EDD\Vendor\Stripe\EphemeralKey::OBJECT_NAME => \EDD\Vendor\Stripe\EphemeralKey::class,
        \EDD\Vendor\Stripe\Event::OBJECT_NAME => \EDD\Vendor\Stripe\Event::class,
        \EDD\Vendor\Stripe\ExchangeRate::OBJECT_NAME => \EDD\Vendor\Stripe\ExchangeRate::class,
        \EDD\Vendor\Stripe\File::OBJECT_NAME => \EDD\Vendor\Stripe\File::class,
        \EDD\Vendor\Stripe\File::OBJECT_NAME_ALT => \EDD\Vendor\Stripe\File::class,
        \EDD\Vendor\Stripe\FileLink::OBJECT_NAME => \EDD\Vendor\Stripe\FileLink::class,
        \EDD\Vendor\Stripe\FinancialConnections\Account::OBJECT_NAME => \EDD\Vendor\Stripe\FinancialConnections\Account::class,
        \EDD\Vendor\Stripe\FinancialConnections\AccountOwner::OBJECT_NAME => \EDD\Vendor\Stripe\FinancialConnections\AccountOwner::class,
        \EDD\Vendor\Stripe\FinancialConnections\AccountOwnership::OBJECT_NAME => \EDD\Vendor\Stripe\FinancialConnections\AccountOwnership::class,
        \EDD\Vendor\Stripe\FinancialConnections\Session::OBJECT_NAME => \EDD\Vendor\Stripe\FinancialConnections\Session::class,
        \EDD\Vendor\Stripe\FundingInstructions::OBJECT_NAME => \EDD\Vendor\Stripe\FundingInstructions::class,
        \EDD\Vendor\Stripe\Identity\VerificationReport::OBJECT_NAME => \EDD\Vendor\Stripe\Identity\VerificationReport::class,
        \EDD\Vendor\Stripe\Identity\VerificationSession::OBJECT_NAME => \EDD\Vendor\Stripe\Identity\VerificationSession::class,
        \EDD\Vendor\Stripe\Invoice::OBJECT_NAME => \EDD\Vendor\Stripe\Invoice::class,
        \EDD\Vendor\Stripe\InvoiceItem::OBJECT_NAME => \EDD\Vendor\Stripe\InvoiceItem::class,
        \EDD\Vendor\Stripe\InvoiceLineItem::OBJECT_NAME => \EDD\Vendor\Stripe\InvoiceLineItem::class,
        \EDD\Vendor\Stripe\Issuing\Authorization::OBJECT_NAME => \EDD\Vendor\Stripe\Issuing\Authorization::class,
        \EDD\Vendor\Stripe\Issuing\Card::OBJECT_NAME => \EDD\Vendor\Stripe\Issuing\Card::class,
        \EDD\Vendor\Stripe\Issuing\CardDetails::OBJECT_NAME => \EDD\Vendor\Stripe\Issuing\CardDetails::class,
        \EDD\Vendor\Stripe\Issuing\Cardholder::OBJECT_NAME => \EDD\Vendor\Stripe\Issuing\Cardholder::class,
        \EDD\Vendor\Stripe\Issuing\Dispute::OBJECT_NAME => \EDD\Vendor\Stripe\Issuing\Dispute::class,
        \EDD\Vendor\Stripe\Issuing\Transaction::OBJECT_NAME => \EDD\Vendor\Stripe\Issuing\Transaction::class,
        \EDD\Vendor\Stripe\LineItem::OBJECT_NAME => \EDD\Vendor\Stripe\LineItem::class,
        \EDD\Vendor\Stripe\LoginLink::OBJECT_NAME => \EDD\Vendor\Stripe\LoginLink::class,
        \EDD\Vendor\Stripe\Mandate::OBJECT_NAME => \EDD\Vendor\Stripe\Mandate::class,
        \EDD\Vendor\Stripe\Order::OBJECT_NAME => \EDD\Vendor\Stripe\Order::class,
        \EDD\Vendor\Stripe\OrderItem::OBJECT_NAME => \EDD\Vendor\Stripe\OrderItem::class,
        \EDD\Vendor\Stripe\OrderReturn::OBJECT_NAME => \EDD\Vendor\Stripe\OrderReturn::class,
        \EDD\Vendor\Stripe\PaymentIntent::OBJECT_NAME => \EDD\Vendor\Stripe\PaymentIntent::class,
        \EDD\Vendor\Stripe\PaymentLink::OBJECT_NAME => \EDD\Vendor\Stripe\PaymentLink::class,
        \EDD\Vendor\Stripe\PaymentMethod::OBJECT_NAME => \EDD\Vendor\Stripe\PaymentMethod::class,
        \EDD\Vendor\Stripe\Payout::OBJECT_NAME => \EDD\Vendor\Stripe\Payout::class,
        \EDD\Vendor\Stripe\Person::OBJECT_NAME => \EDD\Vendor\Stripe\Person::class,
        \EDD\Vendor\Stripe\Plan::OBJECT_NAME => \EDD\Vendor\Stripe\Plan::class,
        \EDD\Vendor\Stripe\Price::OBJECT_NAME => \EDD\Vendor\Stripe\Price::class,
        \EDD\Vendor\Stripe\Product::OBJECT_NAME => \EDD\Vendor\Stripe\Product::class,
        \EDD\Vendor\Stripe\PromotionCode::OBJECT_NAME => \EDD\Vendor\Stripe\PromotionCode::class,
        \EDD\Vendor\Stripe\Quote::OBJECT_NAME => \EDD\Vendor\Stripe\Quote::class,
        \EDD\Vendor\Stripe\Radar\EarlyFraudWarning::OBJECT_NAME => \EDD\Vendor\Stripe\Radar\EarlyFraudWarning::class,
        \EDD\Vendor\Stripe\Radar\ValueList::OBJECT_NAME => \EDD\Vendor\Stripe\Radar\ValueList::class,
        \EDD\Vendor\Stripe\Radar\ValueListItem::OBJECT_NAME => \EDD\Vendor\Stripe\Radar\ValueListItem::class,
        \EDD\Vendor\Stripe\Recipient::OBJECT_NAME => \EDD\Vendor\Stripe\Recipient::class,
        \EDD\Vendor\Stripe\RecipientTransfer::OBJECT_NAME => \EDD\Vendor\Stripe\RecipientTransfer::class,
        \EDD\Vendor\Stripe\Refund::OBJECT_NAME => \EDD\Vendor\Stripe\Refund::class,
        \EDD\Vendor\Stripe\Reporting\ReportRun::OBJECT_NAME => \EDD\Vendor\Stripe\Reporting\ReportRun::class,
        \EDD\Vendor\Stripe\Reporting\ReportType::OBJECT_NAME => \EDD\Vendor\Stripe\Reporting\ReportType::class,
        \EDD\Vendor\Stripe\Review::OBJECT_NAME => \EDD\Vendor\Stripe\Review::class,
        \EDD\Vendor\Stripe\SearchResult::OBJECT_NAME => \EDD\Vendor\Stripe\SearchResult::class,
        \EDD\Vendor\Stripe\SetupAttempt::OBJECT_NAME => \EDD\Vendor\Stripe\SetupAttempt::class,
        \EDD\Vendor\Stripe\SetupIntent::OBJECT_NAME => \EDD\Vendor\Stripe\SetupIntent::class,
        \EDD\Vendor\Stripe\ShippingRate::OBJECT_NAME => \EDD\Vendor\Stripe\ShippingRate::class,
        \EDD\Vendor\Stripe\Sigma\ScheduledQueryRun::OBJECT_NAME => \EDD\Vendor\Stripe\Sigma\ScheduledQueryRun::class,
        \EDD\Vendor\Stripe\SKU::OBJECT_NAME => \EDD\Vendor\Stripe\SKU::class,
        \EDD\Vendor\Stripe\Source::OBJECT_NAME => \EDD\Vendor\Stripe\Source::class,
        \EDD\Vendor\Stripe\SourceTransaction::OBJECT_NAME => \EDD\Vendor\Stripe\SourceTransaction::class,
        \EDD\Vendor\Stripe\Subscription::OBJECT_NAME => \EDD\Vendor\Stripe\Subscription::class,
        \EDD\Vendor\Stripe\SubscriptionItem::OBJECT_NAME => \EDD\Vendor\Stripe\SubscriptionItem::class,
        \EDD\Vendor\Stripe\SubscriptionSchedule::OBJECT_NAME => \EDD\Vendor\Stripe\SubscriptionSchedule::class,
        \EDD\Vendor\Stripe\TaxCode::OBJECT_NAME => \EDD\Vendor\Stripe\TaxCode::class,
        \EDD\Vendor\Stripe\TaxId::OBJECT_NAME => \EDD\Vendor\Stripe\TaxId::class,
        \EDD\Vendor\Stripe\TaxRate::OBJECT_NAME => \EDD\Vendor\Stripe\TaxRate::class,
        \EDD\Vendor\Stripe\Terminal\Configuration::OBJECT_NAME => \EDD\Vendor\Stripe\Terminal\Configuration::class,
        \EDD\Vendor\Stripe\Terminal\ConnectionToken::OBJECT_NAME => \EDD\Vendor\Stripe\Terminal\ConnectionToken::class,
        \EDD\Vendor\Stripe\Terminal\Location::OBJECT_NAME => \EDD\Vendor\Stripe\Terminal\Location::class,
        \EDD\Vendor\Stripe\Terminal\Reader::OBJECT_NAME => \EDD\Vendor\Stripe\Terminal\Reader::class,
        \EDD\Vendor\Stripe\TestHelpers\TestClock::OBJECT_NAME => \EDD\Vendor\Stripe\TestHelpers\TestClock::class,
        \EDD\Vendor\Stripe\ThreeDSecure::OBJECT_NAME => \EDD\Vendor\Stripe\ThreeDSecure::class,
        \EDD\Vendor\Stripe\Token::OBJECT_NAME => \EDD\Vendor\Stripe\Token::class,
        \EDD\Vendor\Stripe\Topup::OBJECT_NAME => \EDD\Vendor\Stripe\Topup::class,
        \EDD\Vendor\Stripe\Transfer::OBJECT_NAME => \EDD\Vendor\Stripe\Transfer::class,
        \EDD\Vendor\Stripe\TransferReversal::OBJECT_NAME => \EDD\Vendor\Stripe\TransferReversal::class,
        \EDD\Vendor\Stripe\UsageRecord::OBJECT_NAME => \EDD\Vendor\Stripe\UsageRecord::class,
        \EDD\Vendor\Stripe\UsageRecordSummary::OBJECT_NAME => \EDD\Vendor\Stripe\UsageRecordSummary::class,
        \EDD\Vendor\Stripe\WebhookEndpoint::OBJECT_NAME => \EDD\Vendor\Stripe\WebhookEndpoint::class,
    ];
}
